Repository tiny-devs/tiny-dungeon-online, pull requests merged in 2020-05, with the labels that each got.

#16 Update Deno installation info
  README.md
Labels: documentation

#20 Add enums for commands and directions
  client/js/client.js
  server/Enums.ts
  server/clientHandler.ts
  server/player.ts
Labels: optimization

#21 Add 8x8 grid for players
  client/js/client.js
Labels: enhancement
